flannel: ./flanneld -etcd-endpoints="http://$MASTER_IP:2379"

docker: sleep 1; ip addr del $(ip addr show dev docker0 | grep inet | awk '{print $2}') dev docker0; sleep 2; export $(cat /var/run/flannel/subnet.env); docker daemon --bip=$FLANNEL_SUBNET --mtu=$FLANNEL_MTU -H unix:///var/run/docker.sock

kubelet: sleep 2; ./kubelet --address=0.0.0.0 --port=10250 --api_servers=http://$MASTER_IP:8080 --logtostderr=true

kube-proxy: sleep 3; ./kube-proxy --master=http://$MASTER_IP:8080 --logtostderr=true
